import { CityId } from '../../types';
import { RoadSegment, TrafficCamera, SignalController, ScenarioConfig } from './transportationTypes';

export const CITY_ROADS: Record<CityId, RoadSegment[]> = {
  taipei: [
    {
      id: 'road-tp-1',
      name: 'Jianguo Elevated Expressway',
      code: 'JG-ELEVATED',
      district: 'Daan - Zhongshan',
      roadType: 'Highway',
      currentSpeed: 28,
      avgSpeed: 60,
      speedLimit: 70,
      vehicleCount: 3100,
      congestionIndex: 82,
      travelTime: 24,
      normalTravelTime: 10,
      density: 'Gridlock',
      coordinates: [
        [25.028, 121.538],
        [25.048, 121.538],
        [25.068, 121.538],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 97,
      alternativeRouteName: 'Fusing South Road',
      alternativeRouteTime: 16,
      aiExplanation: 'High ramp meter queuing at Civic Boulevard exit causing northbound backup.',
      estimatedRecovery: '30 mins',
      hasIncident: true,
    },
    {
      id: 'road-tp-2',
      name: 'Xinyi Road Bus Rapid Transit Corridor',
      code: 'XY-BRT',
      district: 'Xinyi District',
      roadType: 'Bus Route',
      currentSpeed: 42,
      avgSpeed: 45,
      speedLimit: 50,
      vehicleCount: 1850,
      congestionIndex: 40,
      travelTime: 12,
      normalTravelTime: 11,
      density: 'Fluid',
      coordinates: [
        [25.033, 121.565],
        [25.033, 121.545],
        [25.033, 121.525],
      ],
      signalStatus: 'Green Split 65%',
      signalHealth: 99,
      alternativeRouteName: 'Renai Road',
      alternativeRouteTime: 13,
      aiExplanation: 'Dedicated bus lane signal priority active. Minimal delays logged.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-tp-3',
      name: 'Dunhua South Road Boulevard',
      code: 'DH-MAIN',
      district: 'Daan District',
      roadType: 'Primary',
      currentSpeed: 48,
      avgSpeed: 50,
      speedLimit: 60,
      vehicleCount: 2200,
      congestionIndex: 32,
      travelTime: 10,
      normalTravelTime: 9,
      density: 'Fluid',
      coordinates: [
        [25.025, 121.548],
        [25.040, 121.548],
        [25.055, 121.548],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 100,
      alternativeRouteName: 'Guangfu South Road',
      alternativeRouteTime: 11,
      aiExplanation: 'Green wave signal timing synchronized across 6 consecutive intersections.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-tp-4',
      name: 'NTU Hospital Emergency Response Route',
      code: 'EMERG-NTU',
      district: 'Zhongzheng District',
      roadType: 'Emergency',
      currentSpeed: 65,
      avgSpeed: 55,
      speedLimit: 50,
      vehicleCount: 280,
      congestionIndex: 10,
      travelTime: 3,
      normalTravelTime: 5,
      density: 'Fluid',
      coordinates: [
        [25.040, 121.518],
        [25.043, 121.522],
      ],
      signalStatus: 'Manual Override',
      signalHealth: 100,
      alternativeRouteName: 'Zhongshan South Road',
      alternativeRouteTime: 4,
      aiExplanation: 'Emergency vehicle priority route clearing path to National Taiwan University Hospital.',
      estimatedRecovery: 'Clear',
      hasIncident: false,
    },
  ],

};

export const CITY_CAMERAS: Record<CityId, TrafficCamera[]> = {
  taipei: [
    {
      id: 'cam-tp-01',
      name: 'CAM-T01 Jianguo / Civic Blvd Flyover',
      location: 'Zhongshan',
      coordinates: [25.048, 121.538],
      status: 'Recording',
      fps: 30,
      aiVehicleCount: 180,
      averageSpeedDetected: 29,
      snapshotTime: 'Just now',
    },
  ],
};

export const SCENARIO_CONFIGS: ScenarioConfig[] = [
  {
    id: 'accident',
    title: 'Severe Expressway Multi-Vehicle Collision',
    description: 'Simulates a 3-vehicle pileup blocking 2 lanes on a main arterial flyover.',
    iconName: 'AlertOctagon',
    severity: 'critical',
    affectedRoads: ['Jianguo Elevated Rd Northbound', 'Huanhe Expressway Eastbound'],
    impactSummary: '+28% Congestion Spike, Speed drops to 18 km/h, 45 min delay.',
    aiActionPlan: 'Auto-dispatch Highway Patrol, divert traffic to Civic Blvd, add +20s green light phase.',
    addedCongestionIndex: 28,
    speedReductionKm: 25,
  },
  {
    id: 'heavy_rain',
    title: 'Monsoon Flash Rain & Drainage Risk',
    description: 'Simulates intense torrential rainfall reducing visibility and traction.',
    iconName: 'CloudRain',
    severity: 'major',
    affectedRoads: ['Zhongxiao E. Rd', 'Huanhe Expressway Westbound', 'Taipei Ring Rd'],
    impactSummary: 'Hydroplaning risk high, average city arterial speed drops by 35%.',
    aiActionPlan: 'Activate VMS Rain Warning Signs, lower express speed limits to 60 km/h, sync pumps.',
    addedCongestionIndex: 22,
    speedReductionKm: 18,
  },
  {
    id: 'road_closure',
    title: 'Emergency Utility Pipe Burst & Road Closure',
    description: 'Simulates complete 100% closure of a 2-lane key connector road.',
    iconName: 'ShieldAlert',
    severity: 'critical',
    affectedRoads: ['Dunhua N. Rd', 'Zhongxiao Corridor'],
    impactSummary: 'Complete closure, traffic rerouted onto adjacent side streets.',
    aiActionPlan: 'Issue immediate push notification to navigation APIs, adjust 6 surrounding signal timers.',
    addedCongestionIndex: 35,
    speedReductionKm: 30,
  },
  {
    id: 'festival',
    title: 'National Parade & Public Cultural Event',
    description: 'Simulates high pedestrian surges and partial boulevard pedestrianization.',
    iconName: 'Users',
    severity: 'minor',
    affectedRoads: ['Ketagalan Blvd', 'Xinyi BRT'],
    impactSummary: '+15,000 public transit passengers/hr surge, localized slow-downs.',
    aiActionPlan: 'Increase MRT train frequency by +25%, extend pedestrian crossing signals.',
    addedCongestionIndex: 12,
    speedReductionKm: 8,
  },
  {
    id: 'metro_delay',
    title: 'Mass Rapid Transit Signal Fault',
    description: 'Simulates 20-minute train service delay shifting commuters onto road transport.',
    iconName: 'Bus',
    severity: 'major',
    affectedRoads: ['Red Line (Danshui-Xindian)', 'Blue Line (Bannan)'],
    impactSummary: 'Bus stops overflow, taxi/ride-hail demand jumps 300%.',
    aiActionPlan: 'Inject 15 emergency bridging buses, prioritize bus lane green signals.',
    addedCongestionIndex: 18,
    speedReductionKm: 12,
  },
  {
    id: 'vip_movement',
    title: 'High-Level Diplomatic Escort Motorcade',
    description: 'Simulates rolling 10-minute green-wave corridor reservation for diplomatic motorcade.',
    iconName: 'ShieldCheck',
    severity: 'major',
    affectedRoads: ['Xinsheng Overpass', 'Songshan Airport Access Rd'],
    impactSummary: 'Temporary 8-minute hold on intersecting minor roads.',
    aiActionPlan: 'Lock signals on VIP green-wave route, broadcast alternate arterial guidance.',
    addedCongestionIndex: 15,
    speedReductionKm: 10,
  },
  {
    id: 'construction',
    title: 'Overnight Bridge Maintenance Work zone',
    description: 'Simulates single lane reduction for ongoing infrastructural upgrades.',
    iconName: 'Wrench',
    severity: 'minor',
    affectedRoads: ['Huanhe Expressway'],
    impactSummary: 'Minor bottleneck during off-peak and transition hours.',
    aiActionPlan: 'Display early warning light boards 2km ahead, keep lane merge zipper active.',
    addedCongestionIndex: 8,
    speedReductionKm: 5,
  },
];