import { CityId } from '../../types';
import { RoadSegment, TrafficCamera, SignalController, ScenarioConfig } from './transportationTypes';

export const CITY_ROADS: Record<CityId, RoadSegment[]> = {
  singapore: [
    {
      id: 'road-sg-1',
      name: 'Central Expressway (CTE) Northbound',
      code: 'CTE-N',
      district: 'Novena - Ang Mo Kio',
      roadType: 'Highway',
      currentSpeed: 32,
      avgSpeed: 70,
      speedLimit: 80,
      vehicleCount: 3850,
      congestionIndex: 78,
      travelTime: 28,
      normalTravelTime: 14,
      density: 'Heavy',
      coordinates: [
        [1.305, 103.842],
        [1.325, 103.852],
        [1.350, 103.858],
        [1.375, 103.862],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 99,
      alternativeRouteName: 'Upper Serangoon Rd / Thomson Rd',
      alternativeRouteTime: 22,
      aiExplanation: 'Heavy commuter inflow coupled with minor vehicle stalling near exit 7B. Recommended 15% green phase extension at Braddell junction.',
      estimatedRecovery: '25 mins',
      hasIncident: true,
    },
    {
      id: 'road-sg-2',
      name: 'Ayer Rajah Expressway (AYE) Westbound',
      code: 'AYE-W',
      district: 'Clementi - Jurong East',
      roadType: 'Highway',
      currentSpeed: 62,
      avgSpeed: 65,
      speedLimit: 80,
      vehicleCount: 2910,
      congestionIndex: 38,
      travelTime: 16,
      normalTravelTime: 15,
      density: 'Fluid',
      coordinates: [
        [1.272, 103.815],
        [1.290, 103.780],
        [1.312, 103.745],
      ],
      signalStatus: 'Green Split 65%',
      signalHealth: 100,
      alternativeRouteName: 'West Coast Highway',
      alternativeRouteTime: 18,
      aiExplanation: 'Traffic flowing smoothly across all 4 lanes. Speed camera sensors logging average speed of 62 km/h.',
      estimatedRecovery: 'Normal Flow',
      hasIncident: false,
    },
    {
      id: 'road-sg-3',
      name: 'Orchard Road Arterial Boulevard',
      code: 'ORC-MAIN',
      district: 'Orchard / River Valley',
      roadType: 'Primary',
      currentSpeed: 18,
      avgSpeed: 35,
      speedLimit: 50,
      vehicleCount: 2240,
      congestionIndex: 84,
      travelTime: 19,
      normalTravelTime: 8,
      density: 'Gridlock',
      coordinates: [
        [1.304, 103.832],
        [1.301, 103.839],
        [1.298, 103.846],
      ],
      signalStatus: 'Hold Phase',
      signalHealth: 96,
      alternativeRouteName: 'Somerset Rd / Grange Rd',
      alternativeRouteTime: 11,
      aiExplanation: 'Shopping precinct peak drop-offs and bus stop queues causing bottleneck near Scotts Road junction.',
      estimatedRecovery: '35 mins',
      hasIncident: true,
    },
    {
      id: 'road-sg-4',
      name: 'Pan Island Expressway (PIE) Changi Bound',
      code: 'PIE-E',
      district: 'Toa Payoh - Bedok',
      roadType: 'Highway',
      currentSpeed: 54,
      avgSpeed: 62,
      speedLimit: 90,
      vehicleCount: 3420,
      congestionIndex: 52,
      travelTime: 22,
      normalTravelTime: 18,
      density: 'Moderate',
      coordinates: [
        [1.332, 103.850],
        [1.338, 103.885],
        [1.339, 103.920],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 98,
      alternativeRouteName: 'Bartley Viaduct',
      alternativeRouteTime: 20,
      aiExplanation: 'Moderate traffic density near Eunos Flyover. Variable Message Signs (VMS) displaying clear travel time updates.',
      estimatedRecovery: '15 mins',
      hasIncident: false,
    },
    {
      id: 'road-sg-5',
      name: 'Marina Coastal Expressway (MCE)',
      code: 'MCE-TUNNEL',
      district: 'Marina Bay - Tanjong Pagar',
      roadType: 'Highway',
      currentSpeed: 72,
      avgSpeed: 75,
      speedLimit: 80,
      vehicleCount: 2100,
      congestionIndex: 22,
      travelTime: 9,
      normalTravelTime: 8,
      density: 'Fluid',
      coordinates: [
        [1.275, 103.855],
        [1.278, 103.868],
        [1.290, 103.882],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 100,
      alternativeRouteName: 'ECP Highway',
      alternativeRouteTime: 10,
      aiExplanation: 'Tunnel ventilation and safety systems 100% operational. Unobstructed transit throughput.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-sg-6',
      name: 'Upper Thomson Secondary Collector Road',
      code: 'THOM-SEC',
      district: 'Thomson / Bishan',
      roadType: 'Secondary',
      currentSpeed: 45,
      avgSpeed: 50,
      speedLimit: 60,
      vehicleCount: 1450,
      congestionIndex: 35,
      travelTime: 12,
      normalTravelTime: 10,
      density: 'Fluid',
      coordinates: [
        [1.350, 103.835],
        [1.365, 103.832],
        [1.380, 103.828],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 97,
      alternativeRouteName: 'Lornie Highway',
      alternativeRouteTime: 11,
      aiExplanation: 'Secondary collector corridor with steady traffic light cycles.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-sg-7',
      name: 'Bishan Street 22 Residential Access',
      code: 'BSH-RES',
      district: 'Bishan Town',
      roadType: 'Residential',
      currentSpeed: 28,
      avgSpeed: 30,
      speedLimit: 40,
      vehicleCount: 420,
      congestionIndex: 18,
      travelTime: 6,
      normalTravelTime: 5,
      density: 'Fluid',
      coordinates: [
        [1.358, 103.845],
        [1.362, 103.851],
      ],
      signalStatus: 'Green Split 65%',
      signalHealth: 100,
      alternativeRouteName: 'Bishan Road',
      alternativeRouteTime: 5,
      aiExplanation: 'Residential zone with low vehicular volume and pedestrian crossing priorities.',
      estimatedRecovery: 'Normal',
      hasIncident: false,
    },
    {
      id: 'road-sg-8',
      name: 'SGH Medical Rapid Emergency Transit Corridor',
      code: 'EMERG-SGH',
      district: 'Outram - General Hospital',
      roadType: 'Emergency',
      currentSpeed: 68,
      avgSpeed: 60,
      speedLimit: 60,
      vehicleCount: 310,
      congestionIndex: 12,
      travelTime: 4,
      normalTravelTime: 5,
      density: 'Fluid',
      coordinates: [
        [1.280, 103.835],
        [1.285, 103.840],
        [1.290, 103.845],
      ],
      signalStatus: 'Manual Override',
      signalHealth: 100,
      alternativeRouteName: 'Cantonment Road',
      alternativeRouteTime: 6,
      aiExplanation: 'Preemptive green-light emergency corridor activated for ambulances to Singapore General Hospital.',
      estimatedRecovery: 'Clear',
      hasIncident: false,
    },
    {
      id: 'road-sg-9',
      name: 'North-South Corridor Construction Zone',
      code: 'NSC-WORK',
      district: 'Novena Junction',
      roadType: 'Construction',
      currentSpeed: 15,
      avgSpeed: 40,
      speedLimit: 40,
      vehicleCount: 1980,
      congestionIndex: 88,
      travelTime: 25,
      normalTravelTime: 10,
      density: 'Gridlock',
      coordinates: [
        [1.318, 103.845],
        [1.322, 103.848],
      ],
      signalStatus: 'Hold Phase',
      signalHealth: 92,
      alternativeRouteName: 'Balestier Road',
      alternativeRouteTime: 18,
      aiExplanation: 'Major tunneling and viaduct construction narrowing lanes from 3 to 1. Heavy delay expected.',
      estimatedRecovery: '45 mins',
      hasIncident: true,
    },
  ],

  taipei: [
    {
      id: 'road-tp-1',
      name: 'Jianguo Elevated Expressway',
      code: 'JG-ELEVATED',
      district: 'Daan - Zhongshan',
      roadType: 'Highway',
      currentSpeed: 28,
      avgSpeed: 60,
      speedLimit: 70,
      vehicleCount: 3100,
      congestionIndex: 82,
      travelTime: 24,
      normalTravelTime: 10,
      density: 'Gridlock',
      coordinates: [
        [25.028, 121.538],
        [25.048, 121.538],
        [25.068, 121.538],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 97,
      alternativeRouteName: 'Fusing South Road',
      alternativeRouteTime: 16,
      aiExplanation: 'High ramp meter queuing at Civic Boulevard exit causing northbound backup.',
      estimatedRecovery: '30 mins',
      hasIncident: true,
    },
    {
      id: 'road-tp-2',
      name: 'Xinyi Road Bus Rapid Transit Corridor',
      code: 'XY-BRT',
      district: 'Xinyi District',
      roadType: 'Bus Route',
      currentSpeed: 42,
      avgSpeed: 45,
      speedLimit: 50,
      vehicleCount: 1850,
      congestionIndex: 40,
      travelTime: 12,
      normalTravelTime: 11,
      density: 'Fluid',
      coordinates: [
        [25.033, 121.565],
        [25.033, 121.545],
        [25.033, 121.525],
      ],
      signalStatus: 'Green Split 65%',
      signalHealth: 99,
      alternativeRouteName: 'Renai Road',
      alternativeRouteTime: 13,
      aiExplanation: 'Dedicated bus lane signal priority active. Minimal delays logged.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-tp-3',
      name: 'Dunhua South Road Boulevard',
      code: 'DH-MAIN',
      district: 'Daan District',
      roadType: 'Primary',
      currentSpeed: 48,
      avgSpeed: 50,
      speedLimit: 60,
      vehicleCount: 2200,
      congestionIndex: 32,
      travelTime: 10,
      normalTravelTime: 9,
      density: 'Fluid',
      coordinates: [
        [25.025, 121.548],
        [25.040, 121.548],
        [25.055, 121.548],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 100,
      alternativeRouteName: 'Guangfu South Road',
      alternativeRouteTime: 11,
      aiExplanation: 'Green wave signal timing synchronized across 6 consecutive intersections.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-tp-4',
      name: 'NTU Hospital Emergency Response Route',
      code: 'EMERG-NTU',
      district: 'Zhongzheng District',
      roadType: 'Emergency',
      currentSpeed: 65,
      avgSpeed: 55,
      speedLimit: 50,
      vehicleCount: 280,
      congestionIndex: 10,
      travelTime: 3,
      normalTravelTime: 5,
      density: 'Fluid',
      coordinates: [
        [25.040, 121.518],
        [25.043, 121.522],
      ],
      signalStatus: 'Manual Override',
      signalHealth: 100,
      alternativeRouteName: 'Zhongshan South Road',
      alternativeRouteTime: 4,
      aiExplanation: 'Emergency vehicle priority route clearing path to National Taiwan University Hospital.',
      estimatedRecovery: 'Clear',
      hasIncident: false,
    },
  ],

  bengaluru: [
    {
      id: 'road-blr-1',
      name: 'Outer Ring Road (Silk Board to Marathahalli)',
      code: 'ORR-EAST',
      district: 'Bellandur - Tech Corridor',
      roadType: 'Highway',
      currentSpeed: 14,
      avgSpeed: 35,
      speedLimit: 60,
      vehicleCount: 4500,
      congestionIndex: 92,
      travelTime: 48,
      normalTravelTime: 18,
      density: 'Gridlock',
      coordinates: [
        [12.917, 77.623],
        [12.930, 77.680],
        [12.956, 77.701],
      ],
      signalStatus: 'Manual Override',
      signalHealth: 94,
      alternativeRouteName: 'HAL Old Airport Road',
      alternativeRouteTime: 35,
      aiExplanation: 'Metro construction lane narrowing near Bellandur Flyover creating severe bottleneck. Traffic police manual override engaged.',
      estimatedRecovery: '50 mins',
      hasIncident: true,
    },
    {
      id: 'road-blr-2',
      name: 'Hosur Road Elevated Expressway',
      code: 'HSR-EXPRESS',
      district: 'Electronic City',
      roadType: 'Highway',
      currentSpeed: 58,
      avgSpeed: 60,
      speedLimit: 80,
      vehicleCount: 2800,
      congestionIndex: 32,
      travelTime: 15,
      normalTravelTime: 14,
      density: 'Fluid',
      coordinates: [
        [12.910, 77.625],
        [12.850, 77.660],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 98,
      alternativeRouteName: 'Lower Hosur Road',
      alternativeRouteTime: 28,
      aiExplanation: 'Elevated tollway maintains steady speed flow into IT corridor.',
      estimatedRecovery: 'Optimal',
      hasIncident: false,
    },
    {
      id: 'road-blr-3',
      name: '100 Feet Road Indiranagar Primary Arterial',
      code: 'INDR-100FT',
      district: 'Indiranagar',
      roadType: 'Primary',
      currentSpeed: 25,
      avgSpeed: 40,
      speedLimit: 50,
      vehicleCount: 2100,
      congestionIndex: 65,
      travelTime: 20,
      normalTravelTime: 12,
      density: 'Moderate',
      coordinates: [
        [12.970, 77.640],
        [12.980, 77.641],
        [12.990, 77.642],
      ],
      signalStatus: 'Adaptive Sync',
      signalHealth: 96,
      alternativeRouteName: '80 Feet Road',
      alternativeRouteTime: 15,
      aiExplanation: 'Commercial activity and curbside parking slowdowns during peak hours.',
      estimatedRecovery: '20 mins',
      hasIncident: false,
    },
    {
      id: 'road-blr-4',
      name: 'Koramangala 4th Block Secondary Collector',
      code: 'KOR-SEC',
      district: 'Koramangala',
      roadType: 'Secondary',
      currentSpeed: 30,
      avgSpeed: 35,
      speedLimit: 40,
      vehicleCount: 920,
      congestionIndex: 35,
      travelTime: 8,
      normalTravelTime: 7,
      density: 'Fluid',
      coordinates: [
        [12.932, 77.620],
        [12.935, 77.628],
      ],
      signalStatus: 'Green Split 65%',
      signalHealth: 98,
      alternativeRouteName: 'Inner Ring Road',
      alternativeRouteTime: 8,
      aiExplanation: 'Sub-arterial feeder road with steady low-speed local traffic flow.',
      estimatedRecovery: 'Normal',
      hasIncident: false,
    },
    {
      id: 'road-blr-5',
      name: 'Manipal Hospital Emergency Transit Corridor',
      code: 'EMERG-MANIPAL',
      district: 'Old Airport Road',
      roadType: 'Emergency',
      currentSpeed: 60,
      avgSpeed: 50,
      speedLimit: 50,
      vehicleCount: 240,
      congestionIndex: 15,
      travelTime: 5,
      normalTravelTime: 7,
      density: 'Fluid',
      coordinates: [
        [12.958, 77.645],
        [12.960, 77.652],
      ],
      signalStatus: 'Manual Override',
      signalHealth: 100,
      alternativeRouteName: 'Suranjandas Road',
      alternativeRouteTime: 7,
      aiExplanation: 'Hospital ambulance priority route clear of non-essential traffic.',
      estimatedRecovery: 'Clear',
      hasIncident: false,
    },
  ],
};

export const CITY_CAMERAS: Record<CityId, TrafficCamera[]> = {
  singapore: [
    {
      id: 'cam-sg-01',
      name: 'CAM-101 Orchard Road / Scotts Junction',
      location: 'Orchard District',
      coordinates: [1.304, 103.832],
      status: 'Recording',
      fps: 30,
      aiVehicleCount: 142,
      averageSpeedDetected: 21,
      snapshotTime: 'Just now',
    },
    {
      id: 'cam-sg-02',
      name: 'CAM-204 CTE Flyover Northbound',
      location: 'Novena Flyover',
      coordinates: [1.325, 103.852],
      status: 'Recording',
      fps: 30,
      aiVehicleCount: 218,
      averageSpeedDetected: 34,
      snapshotTime: 'Just now',
    },
    {
      id: 'cam-sg-03',
      name: 'CAM-309 AYE / Clementi Road Interchange',
      location: 'Clementi',
      coordinates: [1.290, 103.780],
      status: 'Recording',
      fps: 30,
      aiVehicleCount: 94,
      averageSpeedDetected: 64,
      snapshotTime: 'Just now',
    },
    {
      id: 'cam-sg-04',
      name: 'CAM-412 Marina Coastal Expressway Tunnel',
      location: 'MCE Westbound',
      coordinates: [1.278, 103.868],
      status: 'Recording',
      fps: 60,
      aiVehicleCount: 88,
      averageSpeedDetected: 74,
      snapshotTime: 'Just now',
    },
  ],
  taipei: [
    {
      id: 'cam-tp-01',
      name: 'CAM-T01 Jianguo / Civic Blvd Flyover',
      location: 'Zhongshan',
      coordinates: [25.048, 121.538],
      status: 'Recording',
      fps: 30,
      aiVehicleCount: 180,
      averageSpeedDetected: 29,
      snapshotTime: 'Just now',
    },
  ],
  bengaluru: [
    {
      id: 'cam-blr-01',
      name: 'CAM-B01 Silk Board Junction Optical AI',
      location: 'Silk Board',
      coordinates: [12.917, 77.623],
      status: 'Recording',
      fps: 25,
      aiVehicleCount: 310,
      averageSpeedDetected: 12,
      snapshotTime: 'Just now',
    },
  ],
};

export const SCENARIO_CONFIGS: ScenarioConfig[] = [
  {
    id: 'accident',
    title: 'Severe Expressway Multi-Vehicle Collision',
    description: 'Simulates a 3-vehicle pileup blocking 2 lanes on a main arterial flyover.',
    iconName: 'AlertOctagon',
    severity: 'critical',
    affectedRoads: ['CTE Northbound', 'PIE Eastbound'],
    impactSummary: '+28% Congestion Spike, Speed drops to 18 km/h, 45 min delay.',
    aiActionPlan: 'Auto-dispatch Highway Patrol, divert traffic to Thomson Road, add +20s green light phase.',
    addedCongestionIndex: 28,
    speedReductionKm: 25,
  },
  {
    id: 'heavy_rain',
    title: 'Monsoon Flash Rain & Drainage Risk',
    description: 'Simulates intense torrential rainfall reducing visibility and traction.',
    iconName: 'CloudRain',
    severity: 'major',
    affectedRoads: ['Orchard Road', 'AYE Westbound', 'Outer Ring Road'],
    impactSummary: 'Hydroplaning risk high, average city arterial speed drops by 35%.',
    aiActionPlan: 'Activate VMS Rain Warning Signs, lower express speed limits to 60 km/h, sync pumps.',
    addedCongestionIndex: 22,
    speedReductionKm: 18,
  },
  {
    id: 'road_closure',
    title: 'Emergency Utility Pipe Burst & Road Closure',
    description: 'Simulates complete 100% closure of a 2-lane key connector road.',
    iconName: 'ShieldAlert',
    severity: 'critical',
    affectedRoads: ['Scotts Road', 'Orchard Corridor'],
    impactSummary: 'Complete closure, traffic rerouted onto adjacent side streets.',
    aiActionPlan: 'Issue immediate push notification to navigation APIs, adjust 6 surrounding signal timers.',
    addedCongestionIndex: 35,
    speedReductionKm: 30,
  },
  {
    id: 'festival',
    title: 'National Parade & Public Cultural Event',
    description: 'Simulates high pedestrian surges and partial boulevard pedestrianization.',
    iconName: 'Users',
    severity: 'minor',
    affectedRoads: ['Marina Bay Circuit', 'Xinyi BRT'],
    impactSummary: '+15,000 public transit passengers/hr surge, localized slow-downs.',
    aiActionPlan: 'Increase MRT train frequency by +25%, extend pedestrian crossing signals.',
    addedCongestionIndex: 12,
    speedReductionKm: 8,
  },
  {
    id: 'metro_delay',
    title: 'Mass Rapid Transit Signal Fault',
    description: 'Simulates 20-minute train service delay shifting commuters onto road transport.',
    iconName: 'Bus',
    severity: 'major',
    affectedRoads: ['North-South Line Corridor', 'East-West Line'],
    impactSummary: 'Bus stops overflow, taxi/ride-hail demand jumps 300%.',
    aiActionPlan: 'Inject 15 emergency bridging buses, prioritize bus lane green signals.',
    addedCongestionIndex: 18,
    speedReductionKm: 12,
  },
  {
    id: 'vip_movement',
    title: 'High-Level Diplomatic Escort Motorcade',
    description: 'Simulates rolling 10-minute green-wave corridor reservation for diplomatic motorcade.',
    iconName: 'ShieldCheck',
    severity: 'major',
    affectedRoads: ['MCE Expressway', 'Airport Highway'],
    impactSummary: 'Temporary 8-minute hold on intersecting minor roads.',
    aiActionPlan: 'Lock signals on VIP green-wave route, broadcast alternate arterial guidance.',
    addedCongestionIndex: 15,
    speedReductionKm: 10,
  },
  {
    id: 'construction',
    title: 'Overnight Bridge Maintenance Work zone',
    description: 'Simulates single lane reduction for ongoing infrastructural upgrades.',
    iconName: 'Wrench',
    severity: 'minor',
    affectedRoads: ['Pan Island Expressway'],
    impactSummary: 'Minor bottleneck during off-peak and transition hours.',
    aiActionPlan: 'Display early warning light boards 2km ahead, keep lane merge zipper active.',
    addedCongestionIndex: 8,
    speedReductionKm: 5,
  },
];
